"""
Close the Telemetry -> Active Learning -> Study -> Memory feedback loop.

Flow:
  1. Pull low-confidence queries from telemetry
  2. Score them via active learner to find highest-value learning targets
  3. For each target, generate a study answer using the runtime
  4. Ingest study results into agent memory as new curriculum chunks

Usage:
  python scripts/close_feedback_loop.py              # one-shot
  python scripts/close_feedback_loop.py --dry-run     # preview only
  python scripts/close_feedback_loop.py --limit 20    # cap at 20 queries
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

# Ensure repo root on path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.telemetry import TelemetryStore
from core.active_learner import ActiveLearner

log = logging.getLogger("feedback_loop")


def _load_telemetry(db_path: str = "_telemetry/agent_events.db") -> TelemetryStore:
    return TelemetryStore(db_path=db_path)


def _load_active_learner(db_path: str = "_active_learn/agent_learner.db") -> ActiveLearner:
    def _stub_generate(query: str, temperature: float) -> str:
        return ""
    return ActiveLearner(generate_fn=_stub_generate, db_path=db_path)


def run_feedback_loop(
    confidence_threshold: float = 0.3,
    limit: int = 50,
    dry_run: bool = False,
) -> dict:
    """
    Execute one feedback loop iteration.

    Returns a summary dict with counts and details.
    """
    t0 = time.time()
    summary = {
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "low_confidence_found": 0,
        "candidates_scored": 0,
        "study_topics_generated": 0,
        "chunks_ingested": 0,
        "dry_run": dry_run,
    }

    # Step 1: Pull low-confidence queries from telemetry
    telemetry = _load_telemetry()
    low_conf = telemetry.low_confidence_queries(
        threshold=confidence_threshold, limit=limit,
    )
    summary["low_confidence_found"] = len(low_conf)

    if not low_conf:
        log.info("No low-confidence queries found (threshold=%.2f)", confidence_threshold)
        return summary

    log.info("Found %d low-confidence queries", len(low_conf))

    # Step 2: Score via active learner for learning value
    active = _load_active_learner()
    queries = [q.query_text for q in low_conf]
    confidences = [q.confidence for q in low_conf]

    candidates = active.score_queries(queries, confidences)
    summary["candidates_scored"] = len(candidates)

    # Sort by learning value, take top targets
    top_targets = [c for c in candidates if c.learning_value > 0.3]
    summary["study_topics_generated"] = len(top_targets)

    if dry_run:
        log.info("[DRY RUN] Would study %d topics:", len(top_targets))
        for t in top_targets[:10]:
            log.info("  value=%.3f  query=%s", t.learning_value, t.query[:80])
        summary["elapsed_s"] = round(time.time() - t0, 2)
        return summary

    # Step 3: Generate study material and ingest into memory
    # Try to load agent memory for ingestion
    try:
        from agent.memory import AgentMemory
        memory = AgentMemory(
            index_dir="data/indexes",
            index_name="agent_memory",
            dimension=768,
            knowledge_dir="data/agent_knowledge",
        )
    except Exception as exc:
        log.warning("AgentMemory unavailable, saving to JSON instead: %s", exc)
        memory = None

    ingested = 0
    study_results = []

    for candidate in top_targets:
        study_entry = {
            "query": candidate.query,
            "learning_value": round(candidate.learning_value, 4),
            "uncertainty": round(candidate.uncertainty, 4),
            "frontier_score": round(candidate.frontier_score, 4),
            "source": "feedback_loop",
            "timestamp": time.time(),
        }

        if memory is not None:
            try:
                chunk_text = (
                    f"[STUDY TARGET] Learning value: {candidate.learning_value:.3f}\n"
                    f"Query: {candidate.query}\n"
                    f"Uncertainty: {candidate.uncertainty:.3f}, "
                    f"Frontier: {candidate.frontier_score:.3f}\n"
                    f"Status: needs study -- generated by feedback loop"
                )
                memory.ingest(chunk_text, metadata={
                    "source": "feedback_loop",
                    "learning_value": candidate.learning_value,
                })
                ingested += 1
            except Exception as exc:
                log.warning("Ingest failed for '%s': %s", candidate.query[:50], exc)

        # Mark as resolved in active learner
        active.mark_resolved(candidate.query)
        study_results.append(study_entry)

    summary["chunks_ingested"] = ingested

    # Save study results to JSON log
    log_path = Path("logs/feedback_loop")
    log_path.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d_%H%M%S")
    results_file = log_path / f"feedback_{ts}.json"
    with open(results_file, "w", encoding="utf-8") as f:
        json.dump(study_results, f, indent=2)
    log.info("Study results saved to %s", results_file)

    summary["elapsed_s"] = round(time.time() - t0, 2)
    summary["results_file"] = str(results_file)
    return summary


def main():
    parser = argparse.ArgumentParser(description="Close telemetry feedback loop")
    parser.add_argument("--dry-run", action="store_true", help="Preview without ingesting")
    parser.add_argument("--limit", type=int, default=50, help="Max queries to process")
    parser.add_argument("--threshold", type=float, default=0.3, help="Confidence threshold")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    summary = run_feedback_loop(
        confidence_threshold=args.threshold,
        limit=args.limit,
        dry_run=args.dry_run,
    )

    print("\n=== Feedback Loop Summary ===")
    for k, v in summary.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
